Icl 3759
Consdata/kafka-companion pull request #75
Opened 2020-12-02 09:17 UTC by jdudkowska

2020-12-03 10:31 UTC, ynleborg commented
Miejsca z pomarańczowym kolorem:
- belka wyszukiwania
- cały widok customers
- przeglądanie topiku -> choose partition
- Przyciski Copy to clipboard, Resend w podlgądzie wiadomości

2020-12-03 10:36 UTC, ynleborg requested changes

2020-12-03 10:36 UTC, ynleborg commented on kafka-companion-frontend/src/styles/_palette.scss
> +$primary-base-color: #b31536;
odałem o ogólnym komentarzu te miejsca gdzie jest jeszcze stary kolor

2020-12-11 07:25 UTC, jdudkowska commented on kafka-companion-frontend/src/styles/_palette.scss
> +$primary-base-color: #b31536;
naniosłam poprawki, na belke wyszukiwania zglosilam osobne zadanko

2020-12-13 16:05 UTC, ynleborg approved these changes

2020-12-13 16:05 UTC, merged